assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/stylesheets
    - _assets/images

exclude:
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-28631876-2

name: Kickster

plugins:
  - jekyll-assets
  - jekyll-sitemap

url: http://kickster.nielsenramon.com
