assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-28631876-2

gems:
  - jekyll-assets
  - jekyll-sitemap

name: Kickster

permalink: pretty

url: http://kickster.nielsenramon.com
